### ISSUE TITLE
Spaces in image filenames

### ISSUE THREAD

**Issue by CraigBarlow-WebBox** [clarifynl/responsive-pics#43]
**Describe the bug**
We are using the plugin with some images that have been imported to WP from the clients previous site. Some of the images, annoyingly have spaces in the filename. When the image goes through the plugin and is resized, the resized image filename keeps the spaces in the filenames, which is fine, but when the HTML is outputted, the browser is not accounting for the space as the src attribute is breaking the URL at the first space.

**To Reproduce**
1. Upload an image with a space in the filename
2. Visit front-end where the image should be after the sizes have been generated
3. See error. The image with 404.

**Expected behavior**
The image HTML should output with the usual "%20" in the filename to not break the src URL

**Screenshots**
![Screenshot 2023-04-17 104448](https://user-images.githubusercontent.com/48204747/232449039-a2770a35-9b51-4123-8514-d13553af7676.png)

**Comment by Twansparant** [comment]
Hi @CraigBarlow-WebBox, thanks for this!
Could you provide me with a sample import xml file (assuming you're imported this via the default WordPress Importer plugin) including an image with spaces in the filename? If I upload an image with spaces in the filename, wordpress automatically will convert these to dashes, so this only happens with imported media.
Thanks!
