### ISSUE TITLE
PR 66 probably breaks image resizing

### ISSUE THREAD

**Issue by manuelportela** [clarifynl/responsive-pics#67]
**Describe the bug**
Sorry, I currently do not have much time to file a good issue report I think that PR 66 breaks basic resize functionality

**To Reproduce**
- using current release
- when a new resize is required
- job is scheduled
- finishes without failure
- new file exists returns true
- BUT: file (new resize) does not exist

**Expected behavior**
- resize exists should return true when file exists

**Screenshots**

**Software (please complete the following information):**
- tried in ddev/roots/radicle
- tried in ddev/core install (isolated)
- tried on shared server

**Additional context**
- when rolling back composer req to f5b08c3d06971c9dce60e1e9ef24546980dcc79e it works as expected

**Comment by E-VANCE** [comment]
I can second that.

`v1.8.2` breaks the actual image generation for us, the items are showing up in the Action Scheduler via `process_resize_request` but no files are being rendered / created.

Reverting to `v1.8.1` resolves the issue so #66 must be the culprit here...

**Comment by E-VANCE** [comment]
Correct, **not** using _WP Offload Media_ or similar.

Thanks for looking into this @Twansparant !

**Comment by Twansparant** [comment]
@manuelportela & @E-VANCE I fixed the issue in **version 1.8.3**! 
I didn't check [PR66](https://github.com/clarifynl/responsive-pics/pull/66) properly enough to detect [this](https://github.com/clarifynl/responsive-pics/commit/30eafdffad6f373b709138898c622ae1750ab898) minor mistake...
My bad, sorry for the inconvenience!
